mysite/account/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^login/$',views.user_login,name="user_login"),
    #url(r'^login/$', auth_views.login,name="user_login"),
    url(r'^new_login/$', auth_views.login, {"template_name": "account/login.html"},name="user_login"),
    #url(r'^logout/$', auth_views.logout, name='user_logout'),
    #url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    #url(r'^register/$', auth_views.register,{"template_name": "account/register.html"}, name='user_register'),
    url(r'^register/$', views.register, name='user_register'),
]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.blog_title,name="blog_title"),
    url(r'^content$',views.blog_article,name="blog_article"),
    url(r'^download$',views.download_file, name='user_dl'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import view
from . import main_at 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^account/', include('account.urls',namespace='account',app_name='account')),
    url(r'^home/$',view.home_page),
    url(r'^autotest$', main_at.main_my),

]

mysite/account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class BlogArticles(models.Model):
    title = models.CharField(max_length=30)
    author = models.ForeignKey(User,related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)
 
    def __str__(self):
        return self.title

mysite/account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2= forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model  = User
        fields = ("username", "email")
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd['password2']

mysite/account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from .forms import LoginForm,RegistrationForm

# Create your views here.
def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])

            if user:
                login(request,user)
                return HttpResponse("Welcom you. You have been authenticated successfully")
            else:
                return HttpResponse("sorry, your username or password is not right")
        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request,"account/login.html", {"form":login_form})

def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry, you can't register.")

    else:
        user_form = RegistrationForm()
        return render(request, "account/register.html", {"form": user_form})

mysite/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import BlogArticles
from django.http import HttpResponse
from django.http import StreamingHttpResponse

# Create your views here.
def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs":blogs})

def blog_article(request):#,article_id):
    #article = BlogArticles.objects.get(id=artice_id)
    #pub = article.publish
    return render(request, "blog/content.html")#, {"article":article,"publish":pub})

##################################################################
def download_file(request):
    # do something
    the_file_name='log'
    filename='./log/log'
    response=StreamingHttpResponse(readFile(filename))
    response['Content-Type']='application/octet-stream'
    response['Content-Disposition']='attachment;filename="{0}"'.format(the_file_name)
    return response

def readFile(filename,chunk_size=512):
    with open(filename,'rb') as f:
        while True:
            c=f.read(chunk_size)
            if c:
                yield c
            else:
                break

mysite/blog/templates/blog/content.html
<!DOCTYPE html>
<head>
<title>CONTENT</title>
</head>
<body>
<h1>This is article "1"</h1>
</body>
</html>

mysite/blog/templates/blog/titles.html
<!DOCTYPE html>
<head>
<title>This is title</title>
</head>
<body>
<h1>Hello world!</h1>
</body>
</html>

mysite/templates/home.html
<!DOCTYPE html>
<head>
<title>Home</title>
</head>
<body>
<h1>This is Home page</h1>
<h3>Life is short, we use Python</h3>

<!------------------------------------------------->
<div>
    <ul class="nav navbar-nav navbar-right" stytle="margin-right:10px">
        {% if user.is_authenticated %}
        <li><a href="#">{{ user.username }}</a></li>
        <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
        {% endif %}
    </ul>
</div>

<!------------------------------------------------->
<form action="/autotest" method="post">
    {% csrf_token %}

    <fieldset>

    <p>
    <b>IP Address:</b>
    <select name="web_ip">
    <option value="10.245.36.66">Test server:10.245.36.66</option>
    <option value="10.245.36.98" selected>Test server:10.245.36.98</option>
    <option value="192.168.81.128">Test server:192.168.81.128</option>
    <option value="192.168.81.129">Test server:192.168.81.129</option>
    </select>
    </p>

    <p>
    <b>Vendor:</b>
    <select name="web_vendor">
    <option value="OmniPath">OmniPath</option>
    <option value="Qlogic">Qlogic</option>
    </select>
    </p>

    <p>
    <b>Operate System:</b>
    <select name="web_os_type">
    <option value="RHEL73">RHEL7.3</option>
    <option value="RHEL74">RHEL7.4</option>
    </select>
    </p>


    <p><b>OSS number:</b><input type="text" name="web_oss_number" required></p>

    <p>
    <b>Test case:</b>
    <select name="web_testcase">
    <option value="tc0">TC0:Install Driver</option>
    <option value="tc1">TC1:Install Firmware</option>
    <option value="tc2">TC2:Install driver and firmware</option>
    </select>
    </p>



    <input type="submit" value="Submit">

    </fieldset>
</form>

<form action="/blog/download" method="post">
    {% csrf_token %}

    <fieldset>

    <p>
    <b>IP Address:</b>
    <select name="ip">
    <option value="10.245.36.66">Test server:10.245.36.66</option>
    <option value="192.168.81.130" selected>Test server:192.168.81.130</option>
    </select>
    </p>


    <input type="submit" value="Submit">

    </fieldset>
</form>

<p>Vender  :{{ rlt1 }}</p>
<p>OS      :{{ rlt2 }}</p>
<p>Testcase:{{ rlt3 }}</p>
<p>OSS num :{{ rlt4 }}</p>
<p>opa_tc0 :{{ rlt5 }}</p>
<p>opa_tc1 :{{ rlt6 }}</p>
<p><b>Test result: {{ rlt }}<b></p>





</body>
</html>